workflows:
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**/*']

dependency:
  - changed-files:
    - any-glob-to-any-file: ['package.json']

docker:
  - changed-files:
    - any-glob-to-any-file: ['Dockerfile', 'compose.yaml', '.dockerignore']

bug:
  - head-branch: ['^fix', 'fix', '!code-scanning', '!scanning', '!fix-code-scanning']

github:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']
