name: "Mark and closes stale issues and pull requests"

on:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-issue-stale: 14
        days-before-issue-close: 14
        days-before-pr-stale: 14
        days-before-pr-close: 30
        stale-issue-label: "stale"
        stale-pr-label: "stale"
        stale-issue-message: "This issue has been marked as stale because it has been open for 14 days with no activity."
        close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
        stale-pr-message: "This pull request has been marked as stale because it has been inactive for more than 14 days."
        close-pr-message: "This pull request was closed because it has been inactive for 30 days since being marked as stale."
